### ISSUE TITLE
greasemonkey scripts should end with .user.js

### ISSUE THREAD

**Issue by anarcat** [PatchPorting/front-end#1]
according to the [greasemonkey documentation](https://wiki.greasespot.net/User_Script_Hosting), scripts should end with `.user.js` to be automatically detected by greasemonkey. as is, the suggested script (in https://github.com/PatchPorting/front-end/blob/master/script-plugin.js) doesn't load directly in greasemonkey.

i would be  happy to submit a PR to make that trivial change, unless this is a deliberate decision?

**Comment by jrschwarz** [comment]
Thank you very much for pointing this out. I went ahead and made the change, much appreciated!
